<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>Rkzfps.Windows</RootNamespace>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rkzfps.Core\Rkzfps.Core.csproj" />
  </ItemGroup>
</Project>
